### ISSUE TITLE
Output Zorba as stream, less IO on disk

### ISSUE THREAD

**Issue by mail2morten** [zorba-processor/zorba#18]
Dear Zorba developers,

Im currently using zorba to serialize text to a file.

We are doing for a lot of small files, and I want improve performance with taking away IO overhead.

Writing the data to a file only makes the process more complex, and I would want to stream the result.

Currently I am using zorba.exe like this with Powershell

```
& $zorbaInstallationPath -e input-context=$sourceFileName -f -q $xqueryFile -o $outputFileName  -i --serialize-text -z omit-xml-declaration=yes

return $outputFileName
```

I was hoping and been looking for a way to omit saving the file on disk, and just pass it on as stream/text in memory

I will be looking forward to your answer.

**Comment by mail2morten** [comment]
I foiund that removing '-o $outputFileName' solves my problem, so there is no reason to keep this open. Too bad that no one reacted.

**Comment by cezarfx** [comment]
Hi,

Glad to hear that you solved it, can you share more with us the context in
which you're using Zorba?

Cezar
