### ISSUE TITLE
Version of latest release 3.1.0 or 4.0?

### ISSUE THREAD

**Issue by mgieseki** [zorba-processor/zorba#4]
The latest release is tagged as 4.0 but the version number set in [CMakeList.txt](https://github.com/zorba-processor/zorba/blob/master/CMakeLists.txt#L470) still says 3.1.0. Is this intentional or an oversight?

**Comment by ghislainfourny** [comment]
Hi Martin,

The latest official release is 3.0. The binaries are available to download [here](https://github.com/zorba-processor/zorba/releases/tag/3.0). They were stored by mistake under the 4.0 tag in github, but this has been fixed.

If you wish to build from source, though, the master contains typically more commits than the latest release. This is not officially released, although it is public. It is meant to be used "at your own risks".

I hope it helps!

Kind regards,
Ghislain

**Comment by mgieseki** [comment]
Hi Ghislain,

thanks for the explanation and the additional information. I'm planning to update the zorba package in Fedora and was wondering what version to choose. Since 3.0 is still the latest official release, I'll keep this one for now.

Best,
Martin
